// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars final
Map<String, dynamic> environment = {
  "appConfig": "lib/config/config_en.json",
  "serverConfig": {
    "url": "https://irqcosmetics.com",
    "type": "shopify",
    "accessToken": "14c38b0072f7f0366edb118af974704b",
    "version": "1",
  },
  "defaultDarkTheme": false,
  "enableRemoteConfigFirebase": false,
  "offlineModeConfig": {"enable": false},
  "firebaseAnalyticsConfig": {
    "adStorageConsentGranted": true,
    "enableFirebaseAnalytics": true,
    "adUserDataConsentGranted": true,
    "securityStorageConsentGranted": true,
    "analyticsStorageConsentGranted": true,
    "functionalityStorageConsentGranted": true,
    "personalizationStorageConsentGranted": true,
    "adPersonalizationSignalsConsentGranted": true,
  },
  "enableFacebookAppEvents": true,
  "webProxy": "",
  "maxTextScale": null,
  "loginSMSConstants": {
    "countryCodeDefault": "US",
    "dialCodeDefault": "+1",
    "nameDefault": "United States",
  },
  "phoneNumberConfig": {
    "enable": false,
    "formatInput": false,
    "selectorType": "BOTTOM_SHEET",
    "dialCodeDefault": "+964",
    "showCountryFlag": true,
    "customCountryList": [],
    "countryCodeDefault": "IQ",
    "useInternationalFormat": true,
    "selectorFlagAsPrefixIcon": true,
  },
  "appRatingConfig": {
    "minDays": 7,
    "remindDays": 7,
    "showOnOpen": true,
    "minLaunches": 10,
    "remindLaunches": 10,
    "appStoreIdentifier": "",
    "googlePlayIdentifier": "com.iraqconmetics.app",
  },
  "advanceConfig": {
    "DefaultLanguage": "ar",
    "DetailedBlogLayout": "halfSizeImageType",
    "hideOutOfStock": false,
    "HideEmptyTags": true,
    "HideEmptyCategories": true,
    "EnableRating": true,
    "hideEmptyRating": true,
    "EnableCart": true,
    "ShowBottomCornerCart": true,
    "EnableSkuSearch": false,
    "showStockStatus": false,
    "GridCount": 3,
    "OptimizeImage": {"enable": false, "plugin": "re-generate-image"},
    "httpCache": false,
    "DefaultCurrency": {
      "symbol": "IQD",
      "currency": "iq",
      "countryCode": "IQD",
      "currencyCode": "IQ",
      "decimalDigits": 0,
      "symbolBeforeTheNumber": true,
    },
    "Currencies": [
      {
        "symbol": "IQD",
        "currency": "iq",
        "countryCode": "IQD",
        "currencyCode": "IQ",
        "decimalDigits": 0,
        "symbolBeforeTheNumber": false,
      },
    ],
    "DefaultStoreViewCode": "",
    "EnableAttributesConfigurableProduct": ["color", "size"],
    "isMultiLanguages": true,
    "EnableSyncCartFromWebsite": true,
    "EnableSyncCartToWebsite": true,
    "EnableFirebase": true,
    "RatioProductImage": 1.2,
    "EnableCouponCode": true,
    "ShowCouponList": false,
    "ShowAllCoupons": true,
    "ShowExpiredCoupons": false,
    "AlwaysShowTabBar": false,
    "PrivacyPoliciesPageUrlOrId":
        "https://irqcosmetics.com/policies/privacy-policy",
    "AboutUSPageUrl": "https://codecanyon.net/user/inspireui",
    "NewsPageUrl": "https://products.inspireui.com/",
    "FAQPageUrl": "https://products.inspireui.com/have-a-question/",
    "SupportPageUrl": "https://support.inspireui.com/",
    "DownloadPageUrl": "https://fluxstore.app/",
    "SocialConnectUrl": [
      {
        "url": "https://www.instagram.com/irqcosmetics",
        "icon": "assets/icons/logins/instagram.png",
        "name": "Instagram",
      },
      {
        "url": "https://www.facebook.com/irqcosmetics",
        "icon": "assets/icons/logins/facebook.png",
        "name": "Facebook",
      },
    ],
    "AutoDetectLanguage": false,
    "QueryRadiusDistance": 10,
    "MinQueryRadiusDistance": 1,
    "MaxQueryRadiusDistance": 10,
    "EnableWooCommerceWholesalePrices": false,
    "IsRequiredSiteSelection": false,
    "EnableDeliveryDateOnCheckout": true,
    "EnableNewSMSLogin": false,
    "EnableBottomAddToCart": false,
    "EnableWOOCSCurrencySwitcher": false,
    "enableProductBackdrop": false,
    "enableProductListCategoryMenu": true,
    "categoryImageMenu": true,
    "categoryImageBoxFit": null,
    "EnableDigitsMobileLogin": false,
    "EnableDigitsMobileFirebase": false,
    "EnableDigitsMobileWhatsApp": false,
    "versionCheck": {
      "enable": true,
      "androidId": "com.iraqconmetics.app",
      "androidPlayStoreCountry": " ",
    },
    "AjaxSearchURL": "",
    "AlwaysRefreshBlog": false,
    "OrderNotesLinkSupport": false,
    "inAppUpdateForAndroid": {"enable": true, "typeUpdate": "flexible"},
    "categoryConfig": {"deepLevel": 2, "enableLargeCategories": true},
    "pinnedProductTags": [],
    "showOpeningStatus": true,
    "TimeShowToastMessage": 1500,
    "EnableTeraWalletWithdrawal": false,
    "allowGetDatasByCategoryFilter": true,
    "EnableIsAllData": false,
    "EnableWooSimpleAuction": false,
    "EnableManualAppTrackingTransparency": true,
    "exitAppType": "ExitAppType.requireConfirmPopup",
    "gdpr": {
      "confirmCaptcha": "PERMANENTLY DELETE",
      "showDeleteAccount": true,
      "showPrivacyPolicyFirstTime": false,
    },
    "inAppWebView": false,
    "cartCheckoutButtonLocation": "centerFloat",
  },
  "webViewConfig": {
    "webViewMode": "webViewFlutter",
    "alwaysClearWebViewCache": false,
    "alwaysClearWebViewCookie": false,
    "webViewScript": "",
    "externalDomains": [],
    "internalDomains": [],
  },
  "defaultDrawer": {
    "logo": "assets/images/logo.png",
    "background": null,
    "items": [
      {"type": "home", "show": true},
      {"type": "blog", "show": true},
      {"type": "categories", "show": true},
      {"type": "cart", "show": true},
      {"type": "profile", "show": true},
      {"type": "login", "show": true},
      {"type": "category", "show": true},
    ],
  },
  "wishListConfig": {"type": "normal", "showCartButton": true},
  "defaultSettings": [
    "biometrics",
    "wishlist",
    "notifications",
    "language",
    "currencies",
    "darkTheme",
    "order",
    "rating",
    "privacy",
    "about",
  ],
  "loginSetting": {
    "enable": true,
    "facebookAppId": "",
    "enableRegister": true,
    "IsRequiredLogin": false,
    "appleLoginSetting": {"iOSBundleId": "", "appleAccountTeamID": ""},
    "smsLoginAsDefault": false,
    "facebookClientToken": "",
    "isResetPasswordSupported": true,
    "facebookLoginProtocolScheme": "",
    "requireUsernameWhenRegister": false,
    "showPhoneNumberWhenRegister": false,
    "requirePhoneNumberWhenRegister": false,
  },
  "oneSignalKey": {"enable": false},
  "onBoardingConfig": {
    "data": [
      {"desc": "", "image": "", "title": ""},
      {"desc": "", "image": "https://i.imgur.com/KCkRtvC.png", "title": ""},
      {
        "desc": "Relax and let us bring the style to you",
        "image": "https://i.imgur.com/lbk3KU8.png",
        "title": "Explore your true style",
      },
    ],
    "version": 1,
    "showLanguage": false,
    "enableOnBoarding": false,
    "showLanguagePopup": false,
    "autoCropImageByDesign": false,
    "isOnlyShowOnFirstTime": false,
  },
  "adConfig": {
    "enable": false,
    "facebookTestingId": "",
    "googleTestingId": [],
    "ads": [
      {
        "type": "banner",
        "provider": "google",
        "iosId": "ca-app-pub-3940256099942544/2934735716",
        "androidId": "ca-app-pub-3940256099942544/6300978111",
        "showOnScreens": ["home", "search"],
        "waitingTimeToDisplay": 2,
      },
      {
        "type": "banner",
        "provider": "google",
        "iosId": "ca-app-pub-2101182411274198/5418791562",
        "androidId": "ca-app-pub-2101182411274198/4052745095",
      },
      {
        "type": "interstitial",
        "provider": "google",
        "iosId": "ca-app-pub-3940256099942544/4411468910",
        "androidId": "ca-app-pub-3940256099942544/4411468910",
        "showOnScreens": ["profile"],
        "waitingTimeToDisplay": 5,
      },
      {
        "type": "reward",
        "provider": "google",
        "iosId": "ca-app-pub-3940256099942544/1712485313",
        "androidId": "ca-app-pub-3940256099942544/4411468910",
        "showOnScreens": ["cart"],
      },
      {
        "type": "banner",
        "provider": "facebook",
        "iosId": "IMG_16_9_APP_INSTALL#430258564493822_876131259906548",
        "androidId": "IMG_16_9_APP_INSTALL#430258564493822_489007588618919",
        "showOnScreens": ["home"],
      },
      {
        "type": "interstitial",
        "provider": "facebook",
        "iosId": "430258564493822_489092398610438",
        "androidId": "IMG_16_9_APP_INSTALL#430258564493822_489092398610438",
      },
    ],
    "adMobAppIdIos": "ca-app-pub-7432665165146018~2664444130",
    "adMobAppIdAndroid": "ca-app-pub-7432665165146018~2664444130",
  },
  "dynamicLinkConfig": {
    "type": "fluxDynamicLink",
    "serviceConfigs": {
      "branchIO": {
        "keyLive": "",
        "keyTest": "",
        "testMode": true,
        "liveLinkDomain": "",
        "testLinkDomain": "",
        "liveAlternateLinkDomain": "",
        "testAlternateLinkDomain": "",
      },
      "selfhosted": {},
      "fluxDynamicLink": {
        "iosUrl": null,
        "scheme": "",
        "publicKey": "",
        "androidUrl": null,
        "domainName": "irq-cosmetics-deeplink.fluxbuilder.com",
        "appBundleId": "",
        "androidPackage": "",
      },
    },
  },
  "languagesInfo": [
    {
      "code": "ar",
      "icon": "assets/images/country/ar.png",
      "name": "Arabic",
      "text": "العربية",
      "storeViewCode": "ar",
    },
    {
      "code": "en",
      "icon": "assets/images/country/gb.png",
      "name": "English",
      "text": "English",
      "storeViewCode": "",
    },
    {
      "code": "ku",
      "icon": "assets/images/country/ku.png",
      "name": "Kurdish",
      "text": "Kurdî / کوردی",
      "storeViewCode": "",
    },
  ],
  "paymentConfig": {
    "SmartCOD": null,
    "EnableReview": true,
    "GoogleApiKey": "",
    "EnableAddress": true,
    "GuestCheckout": true,
    "webPaymentIds": [],
    "EnableShipping": true,
    "CheckoutPageSlug": {"en": "checkout"},
    "EnableCreditCard": false,
    "UpdateOrderStatus": false,
    "EnableCustomerNote": true,
    "excludedPaymentIds": [],
    "DefaultStateISOCode": "368",
    "EnableNativeCheckout": false,
    "DefaultCountryISOCode": "IQ",
    "EnableWebviewCheckout": true,
    "allowSearchingAddress": false,
    "CheckoutSuccessPageSlug": [],
    "EnableAddressLocationNote": true,
    "EnableAlphanumericZipCode": false,
    "enableOrderDetailSuccessful": true,
    "PaymentListAllowsCancelAndRefund": [],
    "ShowNativeCheckoutSuccessScreenForWebview": true,
  },
  "payments": {
    "stripe_v2_apple_pay": "assets/icons/payment/apple-pay-mark.svg",
    "stripe_v2_google_pay": "assets/icons/payment/google-pay-mark.png",
    "paypal": "assets/icons/payment/paypal.svg",
    "stripe": "assets/icons/payment/stripe.svg",
    "razorpay": "assets/icons/payment/razorpay.svg",
    "tap": "assets/icons/payment/tap.png",
    "paystack": "assets/icons/payment/paystack.png",
    "myfatoorah_v2": "assets/icons/payment/myfatoorah.png",
    "midtrans": "assets/icons/payment/midtrans.png",
    "xendit_cc": "assets/icons/payment/xendit.png",
    "expresspay_apple_pay": "assets/icons/payment/apple-pay-mark.svg",
    "thai-promptpay-easy": "assets/icons/payment/prompt-pay.png",
    "ppcp-gateway": "assets/icons/payment/paypal.svg",
    "thawani_gw": "assets/icons/payment/thawani.png",
  },
  "payTmConfig": {
    "paymentMethodId": "paytm",
    "merchantId": "your-merchant-id",
    "production": false,
    "enabled": true,
  },
  "inAppPurchaseConfig": {
    "consumableProductIDs": ["com.inspireui.fluxstore.test"],
    "nonConsumableProductIDs": [],
    "subscriptionProductIDs": ["com.inspireui.fluxstore.subscription.test"],
    "enabled": false,
  },
  "expressPayConfig": {
    "paymentMethodId": "shahbandrpay",
    "merchantKey": "b2be2ffc-c8b9-11ed-82a9-42eb4e39c8ae",
    "merchantPassword": "4a00a5fd3c63dd2b743c75746af6ffe2",
    "merchantId": "merchant.com.inspireui.mstore.flutter",
    "production": false,
    "enabled": true,
  },
  "defaultCountryShipping": [
    {"icon": null, "name": "iraq", "emoji": "🇮🇩", "iosCode": "iq"},
  ],
  "googleApiKey": {
    "android": "AIzaSyDSNYVC-8DU9BTcyqkeN9c5pgVhwOBAvGg",
    "ios": "AIzaSyDSNYVC-8DU9BTcyqkeN9c5pgVhwOBAvGg",
    "web": "AIzaSyDSNYVC-8DU9BTcyqkeN9c5pgVhwOBAvGg",
  },
  "productCard": {"defaultImage": "assets/images/no_product_image.png"},
  "productDetail": {
    "boxFit": "contain",
    "height": 0.4,
    "layout": "simpleType",
    "showSku": true,
    "safeArea": false,
    "isSoundOn": true,
    "marginTop": 0,
    "showVideo": false,
    "expandTags": true,
    "showRating": true,
    "showVendor": true,
    "borderRadius": 3,
    "enableReview": false,
    "expandBrands": true,
    "expandInfors": true,
    "allowMultiple": false,
    "autoPlayVideo": true,
    "expandReviews": true,
    "buyButtonStyle": "fixedBottom",
    "showVendorName": false,
    "attributeLayout": "normal",
    "autoPlayGallery": false,
    "limitDayBooking": null,
    "showProductTags": true,
    "showStockStatus": true,
    "sizeGuideConfig": {"url": null, "enable": false, "attributes": []},
    "ShowImageGallery": false,
    "expandCategories": true,
    "expandDescription": true,
    "showRecentProduct": true,
    "showStockQuantity": false,
    "productImageLayout": "page",
    "productMetaDataKey": "",
    "showQuantityInList": false,
    "showRelatedProduct": true,
    "SliderIndicatorType": "dot",
    "alwaysShowBuyButton": true,
    "attributeImagesSize": 50,
    "enableTimeIndicator": false,
    "ForceWhiteBackground": false,
    "showThumbnailAtLeast": 1,
    "allowShareProductData": true,
    "doubleTapToFullScreen": false,
    "productListItemHeight": 125,
    "showProductCategories": false,
    "SliderShowGoBackButton": false,
    "ShowSelectedImageVariant": true,
    "showAddToCartInSearchResult": false,
  },
  "blogDetail": {
    "showHeart": true,
    "showSharing": true,
    "showTextAdjustment": true,
    "enableAudioSupport": false,
    "showAuthorInfo": true,
  },
  "productVariantLayout": {
    "color": "color",
    "size": "box",
    "height": "option",
    "color-image": "image",
  },
  "productAddons": {
    "allowImageType": true,
    "allowVideoType": true,
    "allowCustomType": true,
    "allowedCustomType": ["png", "pdf", "docx"],
    "allowMultiple": false,
    "fileUploadSizeLimit": 5.0,
  },
  "cartDetail": {
    "style": "normal",
    "maxAllowQuantity": 100000000000,
    "minAllowTotalCartValue": 0,
  },
  "productVariantLanguage": {
    "en": {
      "color": "Color",
      "size": "Size",
      "height": "Height",
      "color-image": "Color",
    },
    "ar": {
      "color": "اللون",
      "size": "بحجم",
      "height": "ارتفاع",
      "color-image": "اللون",
    },
    "vi": {
      "color": "Màu",
      "size": "Kích thước",
      "height": "Chiều Cao",
      "color-image": "Màu",
    },
  },
  "saleOffProduct": {
    "ShowCountDown": true,
    "HideEmptySaleOffLayout": false,
    "Color": "#C7222B",
  },
  "notStrictVisibleVariant": true,
  "configChat": {
    "version": "2",
    "iconConfig": {
      "icon": "chat_rounded",
      "size": 32,
      "color": null,
      "fontFamily": "MaterialIcons",
    },
    "hideOnScreens": [],
    "showOnScreens": [],
    "EnableSmartChat": false,
    "enableVendorChat": true,
    "realtimeChatConfig": {
      "enable": false,
      "adminName": "",
      "adminEmail": "",
      "userCanDeleteChat": false,
      "userCanBlockAnotherUser": false,
      "adminCanAccessAllChatRooms": false,
    },
    "wcfmLiveChatConfig": {"enable": false, "adminName": ""},
  },
  "openAIConfig": {
    "enableChat": false,
    "supabaseUrl": "https://rtkrqvtslujdzjxhjocu.supabase.co",
    "supabaseAnonKey":
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0a3JxdnRzbHVqZHpqeGhqb2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzU5OTI5MzMsImV4cCI6MTk5MTU2ODkzM30.qKtfNHhL6AKqGsmDfjMq90bIWIWlnN3UVgnwcLF_vGY",
    "revenueAppleApiKey": "appl_XNtOUZPHwUzelbvwdSezFsMrNeT",
    "revenueGoogleApiKey": "goog_kpDTQdItiHkSrdjDdvLIwAdjOzG",
    "revenueProductsIos": ["gpt_3999_1y_1w0", "gpt_399_1m_1w0"],
    "revenueProductsAndroid": ["gpt_pro_v1"],
    "enableSubscription": false,
    "enableInputKey": false,
  },
  "smartChat": [
    {"app": "", "iconData": "whatsapp"},
  ],
  "deliveryConfig": {
    "appLogo": "assets/images/app_icon_transparent.png",
    "appName": "FluxStore Delivery",
    "dashboardName1": "FluxStore",
    "dashboardName2": "Delivery",
    "enableSystemNotes": false,
  },
  "managerConfig": {
    "appLogo": "assets/images/app_icon_transparent.png",
    "appName": "FluxStore Admin",
    "enableDeliveryFeature": false,
  },
  "loadingIcon": {
    "path":
        "https://raw.githubusercontent.com/fluxbuilder/images/main/2025/11/a5937ab5a22f/1763431246401.png",
    "layout": "image",
  },
  "splashScreen": {
    "type": "fade-in",
    "image":
        "https://raw.githubusercontent.com/fluxbuilder/images/main/2025/11/a5937ab5a22f/1763431270467.png",
    "boxFit": "contain",
    "enable": true,
    "duration": 2000,
    "animationName": "",
    "backgroundColor": "#ffffff",
  },
  "reviewConfig": {
    "service": "judge",
    "maxImage": 2,
    "judgeConfig": {"apiKey": "", "domain": ""},
    "enableReview": false,
    "enableReviewImage": false,
  },
  "orderConfig": {"version": 1},
  "version": "",
  "darkConfig": {
    "logo":
        "https://raw.githubusercontent.com/fluxbuilder/images/main/2025/11/86cd2d199030/1763428593564.png",
    "MainColor": "FFB97A56",
  },
  "lightConfig": {
    "logo":
        "https://raw.githubusercontent.com/fluxbuilder/images/main/2025/11/86cd2d199030/1763428590779.png",
    "MainColor": "FFB97A56",
    "saleColor": "#E15241",
    "backgroundColor": "FFE6D4C4",
  },
  "addressFields": [
    {
      "type": "firstName",
      "visible": true,
      "editable": true,
      "position": 1,
      "required": true,
      "defaultValue": "",
    },
    {
      "type": "lastName",
      "visible": true,
      "editable": true,
      "position": 2,
      "required": true,
      "defaultValue": "",
    },
    {
      "type": "phoneNumber",
      "visible": true,
      "editable": true,
      "position": 3,
      "required": true,
      "defaultValue": "",
    },
    {
      "type": "email",
      "visible": true,
      "editable": true,
      "position": 4,
      "required": false,
      "defaultValue": "",
    },
    {"type": "searchAddress", "visible": false, "position": 5},
    {"type": "selectAddress", "visible": true, "position": 6},
    {"type": "country", "visible": true, "position": 7},
    {"type": "state", "visible": false, "position": 8},
    {
      "type": "city",
      "visible": true,
      "editable": true,
      "position": 9,
      "required": true,
      "defaultValue": "",
    },
    {
      "type": "apartment",
      "visible": true,
      "editable": true,
      "position": 10,
      "required": false,
      "defaultValue": "",
    },
    {
      "type": "block",
      "visible": false,
      "editable": true,
      "position": 11,
      "required": false,
      "defaultValue": "",
    },
    {
      "type": "street",
      "visible": true,
      "editable": true,
      "position": 12,
      "required": true,
      "defaultValue": "",
    },
    {
      "type": "zipCode",
      "visible": false,
      "editable": true,
      "position": 13,
      "required": false,
      "defaultValue": "",
    },
  ],
  "firebaseCerts": {
    "data":
        "\"{\\n  \\\"type\\\": \\\"service_account\\\",\\n  \\\"project_id\\\": \\\"irq-cosmo\\\",\\n  \\\"private_key_id\\\": \\\"ea31384e8b2d5f721640bbc55d8b05976994bd73\\\",\\n  \\\"private_key\\\": \\\"-----BEGIN PRIVATE KEY-----\\\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAUSqkxg5301Nn\\\\nGmGHr+5vlgNp9im7yI586l5trLcD4+6i6W3F9OLJSVKd030fb2snRGIJvH+biMWq\\\\n1JJYv7ccgLtWEWz0zQ8wdu+iNf3Okfg87Us4q+e3j9afuEwiY+CsTrIPu0Bfq5JO\\\\nmY4SOyuVx2I8Qd1B5GfTH7UtoIRCwyTaDUjN0OrYhfISeZ/5Zv2v4N0Z1HD2c32G\\\\nGpTHNwzyjSmRtA0scQRSJX382pIWhOnXx26X+h3BdhbJ8dNCvQD3c43K5peiFLGD\\\\nQIdrqqKqALQm6Y61o5PYTl1zNiOm1/VS4id/PWveEITLOzz9uwJpkvmLqhTYfUj4\\\\nsmyit3PZAgMBAAECggEAANsl0Ulyb0wgCZbK39iOTrO2OFCYN9NdgpRtAXdSAb8C\\\\ne1r+kWQXxwirkpZhjeeXw8L9K5tsq3kWwRFrc56TBxgYmYAXV2x+0r6+mrQ3l/cv\\\\nibYxcwgL1FAcLbXXnNrB+WSOndGokThUobtImO/Et4rBiG+pjrt13lX2pvTozDrg\\\\n0K2uyTI3FDmfLtJyIZQz6EXLMdNul2IKVCmu8NTory5nn+XVtuTxmW/cqDNSNqYL\\\\n9tRmb/eIfTnlSlDB2eRXX8F4hhMueaaYf+Hf4L7RcCz/FLI64UcpoX2+dDlxj2vN\\\\nyxxcUzXUrRFNTA98ULXayCyQmlUm0MAIglTsdBETbQKBgQDrVPNv2efjUr8KoJmO\\\\nGj4q43xIbKJNeE4BtMD6y2+q5bR9hUp82NKOJd35qpF3HgyAMlvW/4AKIiZL2X5F\\\\ntaYltjxY30Dgp2FifW+Cis7TFUXfLpesjBDo9Wm/9amBjJegpoar7eIMHu3Zlerf\\\\nt9YBtehSm+TLTO+qVHlxrcj7ZQKBgQDRNRlcNPmFc3AiLV90vbm2OfGtKbzFly/7\\\\nPnEodb6euniJlb0ebdVarmQPsQVSwwDyQReylYSIZuxqSGXYMtFxRXXaVt4vxuVN\\\\nw/vsgDIK2Q6WB3o3ox+WpAS2x/jawc+F4nN46ax5h+ifd/xrwOivmIzieWjryULX\\\\nBfFbC09hZQKBgFjm0Mgyc62m9tDW9ut98npVUgAyOeY2SpHObRDRha/z8wlwL0GW\\\\nz4QvvfmxfB6Z1XMgkx1XjFFHsVv6H//JraiVfZq9TE8SLHH+nP+d3KBVav3zJg1j\\\\nJIg9HeQMtCpiqG1iO4H77edST9xhDEfTtR8UT13V0ssSl3+rRe2yDzkZAoGBALEh\\\\nBBfNwnX7BzXotKli+ZoP9U9nxyyElVtjwus+xeYee3ACF91roPjmLlIazycDdAmo\\\\nkyfg8BWNDx3trk0eubXt2ZrDcduByyPMi7/xymzk2jSsoA37TwN8W4FmTozpC4uP\\\\n77SwJBfBunNKY63X5yrFPoOByBPak3z6yx8KtGsBAoGAF6Po9PTYEEZzbK3lD/Hh\\\\nyoZEaW4DjgGI7ktzITfymIdLrxU5z/QnG3gZRnLg3ckgaauCDWEr/CdP5DxRlY7v\\\\nLMx2MNyeFl81VUKlQPoRfJqJ2YRtz4ob2zXYfIAfhMa84U9g9iDHC6OimEiDyt0C\\\\nn2E5qfeErvoZIjb6Va7upNk=\\\\n-----END PRIVATE KEY-----\\\\n\\\",\\n  \\\"client_email\\\": \\\"firebase-adminsdk-fbsvc@irq-cosmo.iam.gserviceaccount.com\\\",\\n  \\\"client_id\\\": \\\"117557667810536988913\\\",\\n  \\\"auth_uri\\\": \\\"https://accounts.google.com/o/oauth2/auth\\\",\\n  \\\"token_uri\\\": \\\"https://oauth2.googleapis.com/token\\\",\\n  \\\"auth_provider_x509_cert_url\\\": \\\"https://www.googleapis.com/oauth2/v1/certs\\\",\\n  \\\"client_x509_cert_url\\\": \\\"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40irq-cosmo.iam.gserviceaccount.com\\\",\\n  \\\"universe_domain\\\": \\\"googleapis.com\\\"\\n}\"",
    "filename": "irq-cosmo-firebase-adminsdk-fbsvc-ea31384e8b.json",
  },
  "excludedCategory": "null",
  "colorOverrideConfig": {
    "stockColor": {
      "inStock": "ff3fc1be",
      "backorder": "ffeaa601",
      "outOfStock": "ffe74c3c",
    },
    "ratingColor": {
      "borderStar": "ff3fc1be",
      "primaryStar": "fff39c12",
      "primaryLinearProgress": "fff39c12",
      "backgroundLinearProgress": "fff1f2f3",
    },
    "productFilterColor": {
      "useAccentColor": false,
      "labelColorOpacity": 1,
      "useBackgroundColor": false,
      "usePrimaryColorLight": false,
      "backgroundColorOpacity": 1,
    },
  },
  "shopifyPaymentConfig": {
    "shopName": "",
    "countryCode": "US",
    "applePayConfig": {"enable": false, "merchantId": ""},
    "productionMode": false,
    "googlePayConfig": {
      "enable": false,
      "merchantId": "",
      "stripePublishableKey": "",
    },
    "paymentCardConfig": {"enable": false, "serverEndpoint": ""},
  },
};
